# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Liquid Glass Resources
url: https://liquidglassresources.com # the base hostname & protocol for your site, e.g. http://example.com
permalink: '/:categories/:slug/'
baseurl: "" # the subpath of your site, e.g. /blog
tagline: >- # this means to ignore newlines until "baseurl:"
  Everything you need to elevate your UI with Liquid Glass effects
description: >- # this means to ignore newlines until "baseurl:"
  Everything you need to elevate your UI with Liquid Glass effects

algolia:
  application_id: 'SNYK0RFNCF'
  index_name: 'resources'
  search_api_key: '5c4f681a01931daa54a1008a3429e684'

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/liquid-glass-resources-share-card.png
